import { OrgRole, ProjectRole } from '../enums';
import { PERMISSIONS, type Permission } from './permissions';

const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

/**
 * Permissions granted by organization-level roles.
 *
 * These are evaluated against the user's OrganizationMember.role.
 * They govern what the user can do within the organization context.
 *
 * OWNER  → full platform access within the org
 * ADMIN  → operational access, no billing or org deletion
 * MEMBER → read-only org + project creation + participant management
 */
export const ORG_ROLE_PERMISSIONS: Record<OrgRole, Permission[]> = {
  [OrgRole.OWNER]: ALL_PERMISSIONS,

  [OrgRole.ADMIN]: ALL_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.ORG_DELETE && p !== PERMISSIONS.ORG_MANAGE_BILLING,
  ),

  [OrgRole.MEMBER]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_METADATA_UPDATE,
    PERMISSIONS.PROJECT_FORMAT_UPDATE,
    PERMISSIONS.PROJECT_PHASE_MANAGE,
    PERMISSIONS.PROJECT_MILESTONE_MANAGE,
    PERMISSIONS.PARTICIPANT_CREATE,
    PERMISSIONS.PARTICIPANT_READ,
    PERMISSIONS.PARTICIPANT_UPDATE,
    PERMISSIONS.PERSON_CREATE,
    PERMISSIONS.PERSON_READ,
    PERMISSIONS.PERSON_UPDATE,
    PERMISSIONS.LOCATION_CREATE,
    PERMISSIONS.LOCATION_READ,
    PERMISSIONS.LOCATION_UPDATE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    // Phase 2 — read-only financial access for MEMBER
    PERMISSIONS.BUDGET_TEMPLATE_READ,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_VERSION_READ,
    PERMISSIONS.BUDGET_LINE_READ,
    PERMISSIONS.ACTUAL_READ,
    PERMISSIONS.FINANCE_PLAN_READ,
    // Phase 3 — read-only eligibility / activity access for MEMBER
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_ELIGIBILITY_READ,
    PERMISSIONS.ACTIVITY_DAY_READ,
    PERMISSIONS.EXPENSE_FACT_READ,
    PERMISSIONS.OWNERSHIP_READ,
    PERMISSIONS.RIGHTS_CONTROL_READ,
    PERMISSIONS.RESIDENCY_READ,
    // Phase 4 — read-only program / submission access for MEMBER
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_READ,
    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.PROGRAM_APPLICATION_READ,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.ASSESSMENT_READ,
  ],
};

/**
 * Permissions granted by project-level roles.
 *
 * These are evaluated against the user's ProjectAccess.role for a specific project.
 * Project-level permissions are additive to org-level permissions — they grant
 * access to a specific project even if the user doesn't have an org-wide grant.
 *
 * OWNER  → full project access including deletion and access management
 * EDITOR → read and write, no deletion or access management
 * VIEWER → read-only
 */
export const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Permission[]> = {
  [ProjectRole.OWNER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_MANAGE_ACCESS,
    PERMISSIONS.PROJECT_METADATA_UPDATE,
    PERMISSIONS.PROJECT_FORMAT_UPDATE,
    PERMISSIONS.PROJECT_STAGE_UPDATE,
    PERMISSIONS.PROJECT_PHASE_MANAGE,
    PERMISSIONS.PROJECT_MILESTONE_MANAGE,
    PERMISSIONS.PARTICIPANT_CREATE,
    PERMISSIONS.PARTICIPANT_READ,
    PERMISSIONS.PARTICIPANT_UPDATE,
    PERMISSIONS.PARTICIPANT_DELETE,
    PERMISSIONS.PERSON_CREATE,
    PERMISSIONS.PERSON_READ,
    PERMISSIONS.PERSON_UPDATE,
    PERMISSIONS.LOCATION_CREATE,
    PERMISSIONS.LOCATION_READ,
    PERMISSIONS.LOCATION_UPDATE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
    // Phase 2 — full financial access for project OWNER
    PERMISSIONS.BUDGET_TEMPLATE_READ,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_UPDATE,
    PERMISSIONS.BUDGET_DELETE,
    PERMISSIONS.BUDGET_VERSION_CREATE,
    PERMISSIONS.BUDGET_VERSION_READ,
    PERMISSIONS.BUDGET_VERSION_LOCK,
    PERMISSIONS.BUDGET_LINE_CREATE,
    PERMISSIONS.BUDGET_LINE_READ,
    PERMISSIONS.BUDGET_LINE_UPDATE,
    PERMISSIONS.BUDGET_LINE_DELETE,
    PERMISSIONS.BUDGET_LINE_ANNOTATE,
    PERMISSIONS.ACTUAL_CREATE,
    PERMISSIONS.ACTUAL_READ,
    PERMISSIONS.ACTUAL_UPDATE,
    PERMISSIONS.ACTUAL_DELETE,
    PERMISSIONS.FINANCE_PLAN_CREATE,
    PERMISSIONS.FINANCE_PLAN_READ,
    PERMISSIONS.FINANCE_PLAN_UPDATE,
    PERMISSIONS.FINANCE_PLAN_DELETE,
    // Phase 3 — full eligibility access for project OWNER
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_DELETE,
    PERMISSIONS.VENDOR_ELIGIBILITY_CREATE,
    PERMISSIONS.VENDOR_ELIGIBILITY_READ,
    PERMISSIONS.VENDOR_ELIGIBILITY_UPDATE,
    PERMISSIONS.ACTIVITY_DAY_CREATE,
    PERMISSIONS.ACTIVITY_DAY_READ,
    PERMISSIONS.ACTIVITY_DAY_UPDATE,
    PERMISSIONS.ACTIVITY_DAY_DELETE,
    PERMISSIONS.EXPENSE_FACT_CREATE,
    PERMISSIONS.EXPENSE_FACT_READ,
    PERMISSIONS.EXPENSE_FACT_UPDATE,
    PERMISSIONS.EXPENSE_FACT_DELETE,
    PERMISSIONS.OWNERSHIP_CREATE,
    PERMISSIONS.OWNERSHIP_READ,
    PERMISSIONS.OWNERSHIP_UPDATE,
    PERMISSIONS.OWNERSHIP_DELETE,
    PERMISSIONS.RIGHTS_CONTROL_CREATE,
    PERMISSIONS.RIGHTS_CONTROL_READ,
    PERMISSIONS.RIGHTS_CONTROL_UPDATE,
    PERMISSIONS.RIGHTS_CONTROL_DELETE,
    PERMISSIONS.RESIDENCY_CREATE,
    PERMISSIONS.RESIDENCY_READ,
    PERMISSIONS.RESIDENCY_UPDATE,
    // Phase 4 — full program enrollment/submission access for project OWNER
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_CREATE,
    PERMISSIONS.PROJECT_PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_UPDATE,
    PERMISSIONS.PROJECT_PROGRAM_DELETE,
    PERMISSIONS.SUBMISSION_CREATE,
    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_UPDATE,
    PERMISSIONS.SUBMISSION_DELETE,
    PERMISSIONS.PROGRAM_APPLICATION_CREATE,
    PERMISSIONS.PROGRAM_APPLICATION_READ,
    PERMISSIONS.PROGRAM_APPLICATION_UPDATE,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_UPDATE,
    PERMISSIONS.EVIDENCE_DELETE,
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.ASSESSMENT_UPDATE,
  ],

  [ProjectRole.EDITOR]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_METADATA_UPDATE,
    PERMISSIONS.PROJECT_FORMAT_UPDATE,
    PERMISSIONS.PROJECT_PHASE_MANAGE,
    PERMISSIONS.PROJECT_MILESTONE_MANAGE,
    PERMISSIONS.PARTICIPANT_CREATE,
    PERMISSIONS.PARTICIPANT_READ,
    PERMISSIONS.PARTICIPANT_UPDATE,
    PERMISSIONS.PERSON_CREATE,
    PERMISSIONS.PERSON_READ,
    PERMISSIONS.PERSON_UPDATE,
    PERMISSIONS.LOCATION_CREATE,
    PERMISSIONS.LOCATION_READ,
    PERMISSIONS.LOCATION_UPDATE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    // Phase 2 — read + write, no delete/lock
    PERMISSIONS.BUDGET_TEMPLATE_READ,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_UPDATE,
    PERMISSIONS.BUDGET_VERSION_CREATE,
    PERMISSIONS.BUDGET_VERSION_READ,
    PERMISSIONS.BUDGET_LINE_CREATE,
    PERMISSIONS.BUDGET_LINE_READ,
    PERMISSIONS.BUDGET_LINE_UPDATE,
    PERMISSIONS.BUDGET_LINE_ANNOTATE,
    PERMISSIONS.ACTUAL_CREATE,
    PERMISSIONS.ACTUAL_READ,
    PERMISSIONS.ACTUAL_UPDATE,
    PERMISSIONS.FINANCE_PLAN_CREATE,
    PERMISSIONS.FINANCE_PLAN_READ,
    PERMISSIONS.FINANCE_PLAN_UPDATE,
    // Phase 3 — read + write for EDITOR (no delete)
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_ELIGIBILITY_CREATE,
    PERMISSIONS.VENDOR_ELIGIBILITY_READ,
    PERMISSIONS.VENDOR_ELIGIBILITY_UPDATE,
    PERMISSIONS.ACTIVITY_DAY_CREATE,
    PERMISSIONS.ACTIVITY_DAY_READ,
    PERMISSIONS.ACTIVITY_DAY_UPDATE,
    PERMISSIONS.EXPENSE_FACT_CREATE,
    PERMISSIONS.EXPENSE_FACT_READ,
    PERMISSIONS.EXPENSE_FACT_UPDATE,
    PERMISSIONS.OWNERSHIP_CREATE,
    PERMISSIONS.OWNERSHIP_READ,
    PERMISSIONS.OWNERSHIP_UPDATE,
    PERMISSIONS.RIGHTS_CONTROL_CREATE,
    PERMISSIONS.RIGHTS_CONTROL_READ,
    PERMISSIONS.RIGHTS_CONTROL_UPDATE,
    PERMISSIONS.RESIDENCY_CREATE,
    PERMISSIONS.RESIDENCY_READ,
    PERMISSIONS.RESIDENCY_UPDATE,
    // Phase 4 — read + write for EDITOR (no delete)
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_CREATE,
    PERMISSIONS.PROJECT_PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_UPDATE,
    PERMISSIONS.SUBMISSION_CREATE,
    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_UPDATE,
    PERMISSIONS.PROGRAM_APPLICATION_CREATE,
    PERMISSIONS.PROGRAM_APPLICATION_READ,
    PERMISSIONS.PROGRAM_APPLICATION_UPDATE,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_UPDATE,
    PERMISSIONS.ASSESSMENT_READ,
  ],

  [ProjectRole.VIEWER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PARTICIPANT_READ,
    PERMISSIONS.PERSON_READ,
    PERMISSIONS.LOCATION_READ,
    PERMISSIONS.DOCUMENT_READ,
    // Phase 2 — read-only financial access
    PERMISSIONS.BUDGET_TEMPLATE_READ,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_VERSION_READ,
    PERMISSIONS.BUDGET_LINE_READ,
    PERMISSIONS.ACTUAL_READ,
    PERMISSIONS.FINANCE_PLAN_READ,
    // Phase 3 — read-only eligibility access
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_ELIGIBILITY_READ,
    PERMISSIONS.ACTIVITY_DAY_READ,
    PERMISSIONS.EXPENSE_FACT_READ,
    PERMISSIONS.OWNERSHIP_READ,
    PERMISSIONS.RIGHTS_CONTROL_READ,
    PERMISSIONS.RESIDENCY_READ,
    // Phase 4 — read-only program/submission access
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_PROGRAM_READ,
    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.PROGRAM_APPLICATION_READ,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.ASSESSMENT_READ,
  ],
};

/**
 * Resolves whether a given org role grants a permission.
 */
export function orgRoleHasPermission(role: OrgRole, permission: Permission): boolean {
  return ORG_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/**
 * Resolves whether a given project role grants a permission.
 */
export function projectRoleHasPermission(role: ProjectRole, permission: Permission): boolean {
  return PROJECT_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/**
 * Returns true if the user has the permission via either their org role
 * or their project-specific role. Project role is only evaluated when provided.
 */
export function hasPermission(
  orgRole: OrgRole,
  permission: Permission,
  projectRole?: ProjectRole,
): boolean {
  if (orgRoleHasPermission(orgRole, permission)) return true;
  if (projectRole && projectRoleHasPermission(projectRole, permission)) return true;
  return false;
}
