/**
 * Shared types for pure provincial grant estimators.
 *
 * These mirror the input shape used by the original `incentives-app/credits`
 * calculators. Estimators are intentionally decoupled from NestJS, Prisma, and
 * StoryOS domain models: the adapter in `grant-estimator.service.ts` is
 * responsible for projecting StoryOS data (BudgetLine / ExpenseFact /
 * ActivityDay / Ownership / Rights) onto these shapes.
 */

/** Single budget or actual line as seen by a pure estimator. */
export interface EstimatorLine {
  /** Coarse classification: 'Labour' or 'NonLabour'. Estimators only need the 'Labour' marker. */
  type: 'Labour' | 'NonLabour';
  /** ISO-like 2-letter province code, e.g. 'ON', 'BC', 'AB', 'MB'. May be empty for non-located lines. */
  province: string;
  /** Account-level category. Estimators test this with /post/i to detect post-production lines. */
  category?: string;
  /** Activity tag. Estimators test for the literal 'VFX_Animation' to enable VFX/animation tiers. */
  activity?: string;
  /** Line amount in dollars. */
  amount?: number;
  /** Human-readable description (useful for tracing/debugging) */
  description?: string;
  /** General ledger / Account code */
  glCode?: string;
  /** High level category from the budget template (e.g. ABOVE_THE_LINE) */
  budgetTemplateCategory?: string;
  /** True when this line is fully ineligible for tax credit calculations. */
  taxCreditIneligible?: boolean;
  /**
   * Fraction of line amount that is ineligible (0 = fully eligible, 1 = fully
   * ineligible, 0.5 = 50% ineligible). Takes precedence over `taxCreditIneligible`
   * when present. Used for partial ineligibility rules like 50% meals/craft services.
   */
  ineligiblePortion?: number;
}

/**
 * Free-form options passed to estimators. Each provincial estimator reads
 * only the keys it cares about; unknown keys are ignored.
 */
export interface EstimatorOpts {
  // Day-based regional weighting (used by ON, BC, MB, AB)
  totalDays?: number;
  daysProvincial?: number;
  daysDistant?: number;

  // Ontario-specific switches
  onStream?: 'OPSTC' | 'OCASE';
  onOutsideGTA?: boolean;
  onOutsideEntireGTA?: boolean;

  // BC-specific toggles
  bcRegionalOn?: boolean;
  bcDistantOn?: boolean;
  bcDaveOn?: boolean;

  // Manitoba-specific toggles
  mbRuralOn?: boolean;
  mbNorthernOn?: boolean;
  mbOwnershipOn?: boolean;

  // Allow forward-compat passthrough without weakening typing for the rest
  [key: string]: unknown;
}

/** Assistance already generated by upstream programs in a scenario. */
export interface EstimatorPriorAssistance {
  total?: number;
  labour?: number;
  nonLabour?: number;
}

/** Metadata passed to estimators that need ownership/rights context (currently AB only). */
export interface EstimatorMeta {
  provincialOwnershipPercent?: number;
  copyright?: {
    holderName?: string;
    jurisdiction?: {
      country?: string;
      province?: string;
    };
  };
  [key: string]: unknown;
}

export interface EstimatorTraceLine {
  description?: string;
  glCode?: string;
  budgetTemplateCategory?: string;
  type: string;
  province: string;
  amount: number;
  included: boolean;
  reason?: string;
  /** When present and < 1, only this fraction of the amount was included in the base. */
  eligibleFraction?: number;
}

/** Standard return shape from each provincial estimator entry-point. */
export interface EstimatorResult {
  amount: number;
  detail: string;
  trace?: {
    lines: EstimatorTraceLine[];
    [key: string]: unknown;
  };
}
